apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "" 
  install:
    createNamespace: false
  values:
    adminUser: admin
    adminPassword: prom-operator
    persistence:
      enabled: false
