apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kiali-server
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
      version: ""
  install:
    createNamespace: false
  values:
    auth:
      strategy: anonymous
