apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: demo-app
build:
  artifacts:
    - image: demo-app:local-v1
      context: app/v1
      docker:
        dockerfile: Dockerfile
    - image: demo-app:local-v2
      context: app/v2
      docker:
        dockerfile: Dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - k8s/base/namespace.yaml
      - k8s/base/deployment.yaml
      - k8s/base/deployment-v2.yaml
      - k8s/base/service.yaml
      - k8s/istio/*.yaml
