apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tmwaas/aws-cloud-infra-project  
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
