apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-v2
  labels:
    app: demo-app
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      version: v2
  template:
    metadata:
      labels:
        app: demo-app
        version: v2
    spec:
      containers:
        - name: app
          image: demo-app:local-v2
          ports:
            - containerPort: 8080
